version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: rag_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rag_base
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # 1. Пробрасываем корень проекта, чтобы изменения в коде подхватывались сразу
      - .:/app
      # 2. Пробрасываем папку с кэшем моделей
      - ./cache:/app/cache
      # 3. (Важно) Пробрасываем папку с твоим CSV файлом
      - ./data:/app/data
    environment:
      - SENTENCE_TRANSFORMERS_HOME=/app/cache
      # Оставляем хост 'db', так как запускать будем ВНУТРИ докера
      - DATABASE_URL=postgresql://admin:admin@db:5432/rag_base
volumes:
  postgres_data: